[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "marp-presentations"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
python = ">=3.12.5,<4"
numpy = ">=2.1.1,<3"
jax = ">=0.4.31,<0.5"
jaxlib = ">=0.4.31,<0.5"
